@echo off
rem This script automatically generates `qml.qrc` on Windows.
rem Notice: Only call this script on the root path of this project.

rem Initial works.
setlocal enabledelayedexpansion
set ROOT_PATH=%CD%
set REL_PATH=\src\
set QRC_FILE=qml.qrc
set FULL_TARGET_PATH=%ROOT_PATH%%REL_PATH%%QRC_FILE%

rem Create the file and write its header.
echo Starting to generate `qml.qrc`...
echo ^<^^!-- This file is automatically generated by `generate_qrc.bat`. --^> > %FULL_TARGET_PATH%
echo ^<^^!DOCTYPE RCC^>^<RCC version="1.0"^> >> %FULL_TARGET_PATH%
echo ^    ^<qresource prefix="/"^> >> %FULL_TARGET_PATH%

rem Add the files to the target.
call :inform %cd%\src\assets
call :inform %cd%\src\ui

rem Final works.
echo ^    ^</qresource^> >> %FULL_TARGET_PATH%
echo ^</RCC^> >> %FULL_TARGET_PATH%
echo Finished to generate `qml.qrc`.
exit 0

rem A function to add all files of a directory into the file.
rem %~1: The root path of the loop.
:add
for /R %~1 %%F in (*) do (
    rem Calculate the relative path.
    set "filePath=%%F"
    rem TODO: Currently we can only deal with `src/*`.
    set "relativePath=!filePath:%cd%\src\=!"
    set "relativePath=!relativePath:\=/!"

    if %%~nxF neq README.txt (
        echo ^        ^<file^> !relativePath! ^</file^> >> %FULL_TARGET_PATH%
    )
)
goto :eof

rem Add the files to the file and inform the user.
:inform
echo Reading directory %~1
call :add %~1
goto :eof

endlocal