-- As `qml.qrc` does not support wildcards, we have to put the files into
-- `qml.qrc` mannually, and that's what this script does.

local lfs = require("lfs")

local src_root_path = "../src"
local qrc_file_name = "qml.qrc"

-- Test the current path.
print(src_root_path..qrc_file_name)

--[[
-- Open the file and get ready to write.
local target_file = io.open(src_root_path..qrc_file_name, 'w')
if (target_file==nil) then
    error("`generate_qrc.lua` failed to create file `qml.qrc`.")
end
target_file:write('<!-- This file is automatically generated by `generate_qrc.lua`. -->\n')
target_file:write('<!DOCTYPE RCC><RCC version="1.0">\n')
target_file:write('    <qresource prefix="/">\n')

-- How to add all files of a path.
local function add_files(dir)
    for file in lfs.dir(dir) do
        if file~='.' and file~='..' and file~='README.txt' then
            local path = dir .. '/' .. file
            local attr = lfs.attributes(path)
            if attr.mode == "directory" then
                add_files(path)
            else
                target_file:write("        <file>"..path.."</file>")
            end
        end
    end
end

-- Which directories should be added.
add_files(src_root_path .. '/' .. "assets")
add_files(src_root_path .. '/' .. "ui")

-- Final works.
target_file:write("    </qresource>")
target_file:write("</RCC>")
]]--